# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/XME0715/SDK_Demo/21_double_ov5640_hdmi/double_ov5640/double_ov5640.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_1/design_1_v_vid_in_axi4s_0_1.xci
# IP: The module: 'design_1_v_vid_in_axi4s_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/XME0715/SDK_Demo/21_double_ov5640_hdmi/double_ov5640/double_ov5640.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_1/design_1_v_vid_in_axi4s_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_vid_in_axi4s_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/XME0715/SDK_Demo/21_double_ov5640_hdmi/double_ov5640/double_ov5640.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_1/design_1_v_vid_in_axi4s_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_vid_in_axi4s_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/XME0715/SDK_Demo/21_double_ov5640_hdmi/double_ov5640/double_ov5640.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_1/design_1_v_vid_in_axi4s_0_1.xci
# IP: The module: 'design_1_v_vid_in_axi4s_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/XME0715/SDK_Demo/21_double_ov5640_hdmi/double_ov5640/double_ov5640.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_1/design_1_v_vid_in_axi4s_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_vid_in_axi4s_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/XME0715/SDK_Demo/21_double_ov5640_hdmi/double_ov5640/double_ov5640.srcs/sources_1/bd/design_1/ip/design_1_v_vid_in_axi4s_0_1/design_1_v_vid_in_axi4s_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_v_vid_in_axi4s_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
